import type { Metadata } from "next";
import Link from "next/link";
import {
  HelpSectionHeading,
  HelpTexturedBand,
  PublicHelpShell,
} from "@/app/_components/PublicHelpShell";

export const metadata: Metadata = {
  title: "Voter Help | halal. OLPS COMELEC",
  description: "A practical guide to OLPS COMELEC voter credentials, ballots, receipts, and receipt verification.",
};

const steps = [
  ["01", "Receive your voter slip", "COMELEC provides your Student ID and election-specific Control Number. Keep both private."],
  ["02", "Open your ballot", "Go to the voting page while your division's election is open and enter the details exactly as printed."],
  ["03", "Review every position", "Choose candidates, leave positions blank only if you mean to abstain, then check the final review screen."],
  ["04", "Save the receipt code", "After submission, copy or print the one-time receipt code shown on the confirmation page."],
];

export default function VoterHelpPage() {
  return (
    <PublicHelpShell
      eyebrow="Student Voter Guide"
      title="Voter Help"
      description="Use this guide when you receive your voter slip, cast your OLPS COMELEC ballot, and keep your receipt code for later verification."
    >
      <section className="px-[27px] py-[72px]">
        <div className="mx-auto max-w-5xl">
          <HelpSectionHeading
            eyebrow="Your Voter Slip"
            title="Two details open one ballot"
            body="Your Student ID identifies the roster entry. Your Control Number authorizes one ballot for that election. The submitted ballot is stored separately from both details."
          />

          <div className="mt-[45px] grid gap-[23px] md:grid-cols-2">
            <CredentialCard
              label="Student ID"
              example="2026-0001"
              body="Your school-issued identifier confirms that the person using the voter slip matches a student registered in that election's roster."
              points={[
                "Format: four digits, a hyphen, then four digits",
                "Always use your own Student ID",
                "A Student ID alone cannot open a ballot",
              ]}
            />
            <CredentialCard
              label="Control Number"
              example="2611A001"
              body="A unique, election-specific code generated by COMELEC for one voter roster entry. It is a voting credential, so do not share it."
              points={[
                "26 = year, 11 = grade, A = section, 001 = sequence",
                "Letters are entered in uppercase",
                "The code cannot cast another ballot after submission",
              ]}
            />
          </div>

          <div className="mt-[27px] border border-gold/20 bg-gold/5 p-[23px]">
            <p className="font-heading text-[17px] font-bold uppercase tracking-[0.12em] text-gold">Why both are required</p>
            <p className="mt-[10px] text-[17px] leading-[27px] text-white/55">
              The Student ID identifies the registered student, while the Control Number authorizes that student&apos;s one ballot for a specific election. Voter records track whether the roster entry has voted. Candidate choices are stored under an anonymous ballot record, not under the Student ID or Control Number.
            </p>
          </div>
        </div>
      </section>

      <section className="relative overflow-hidden border-y border-gold/10 px-[27px] py-[72px]">
        <HelpTexturedBand />
        <div className="relative z-10 mx-auto max-w-5xl">
          <HelpSectionHeading
            eyebrow="Voting Steps"
            title="From voter slip to receipt"
            body="Voting is available only while your division's election is open. Once accepted, the same Control Number cannot be used again."
          />
          <div className="mt-[45px] grid gap-[19px] sm:grid-cols-2 lg:grid-cols-4">
            {steps.map(([number, title, body]) => (
              <article key={number} className="border border-white/8 bg-navy/50 p-[23px]">
                <span className="font-mono text-[14px] text-gold/60">{number}</span>
                <h3 className="mt-[19px] font-heading text-[19px] font-bold text-white/90">{title}</h3>
                <p className="mt-[10px] text-[14px] leading-[23px] text-white/45">{body}</p>
              </article>
            ))}
          </div>
        </div>
      </section>

      <section className="px-[27px] py-[72px]">
        <div className="mx-auto max-w-5xl">
          <HelpSectionHeading
            eyebrow="Receipt & Verification"
            title="Keep the code private"
            body="The confirmation page shows your receipt code once. Anyone with that code can verify that receipt, so treat it like election paperwork."
          />
          <div className="mt-[45px] grid gap-[23px] md:grid-cols-3">
            <ReceiptCard title="Receipt code">
              The receipt code is shown after your ballot is accepted. It cannot be recovered later because the system stores only its hash.
            </ReceiptCard>
            <ReceiptCard title="Recorded choices">
              The confirmation page shows how your anonymous ballot was recorded. Review it before leaving the page.
            </ReceiptCard>
            <ReceiptCard title="Verify your receipt">
              Use the Verify page later to check that the anonymous ballot remains included and unchanged. Each receipt can be verified once.
            </ReceiptCard>
          </div>
        </div>
      </section>

      <section className="px-[27px] pb-[72px]">
        <div className="mx-auto max-w-5xl">
          <HelpSectionHeading
            eyebrow="Common Questions"
            title="When something goes wrong"
            body="Do not try another student's credentials. Contact COMELEC so the roster can be checked safely."
          />
          <div className="mt-[45px] grid gap-[19px] md:grid-cols-2">
            <Question title="My credentials are rejected">
              Check the Student ID format, uppercase the Control Number, and confirm that your division&apos;s election is open. If it still fails, bring the voter slip to COMELEC.
            </Question>
            <Question title="I lost or damaged my voter slip">
              Report it directly to COMELEC. Do not ask another student for their Control Number and do not send voter credentials through group chats.
            </Question>
            <Question title="The page says I already voted">
              Stop and report the message to COMELEC. A Control Number is accepted only once, even if the browser is closed after submission.
            </Question>
            <Question title="When can I see results?">
              Public results remain hidden while voting is open. They become available after the election is closed and COMELEC releases the final results.
            </Question>
          </div>

          <div className="mt-[36px] flex flex-wrap items-center justify-between gap-[19px] border border-white/8 bg-white/2.5 p-[23px]">
            <div>
              <h3 className="font-heading font-bold text-white/90">Have your voter slip ready?</h3>
              <p className="mt-[5px] text-[14px] text-white/45">Continue when your division&apos;s election is open.</p>
            </div>
            <Link href="/vote" className="bg-gold px-[23px] py-[14px] font-heading text-[14px] font-bold uppercase tracking-[0.16em] text-navy-deep transition-opacity hover:opacity-90">
              Open voting page
            </Link>
          </div>
        </div>
      </section>
    </PublicHelpShell>
  );
}

function CredentialCard({
  label,
  example,
  body,
  points,
}: {
  label: string;
  example: string;
  body: string;
  points: string[];
}) {
  return (
    <article className="border border-white/8 bg-navy/50 p-[27px]">
      <p className="text-[12px] uppercase tracking-[0.25em] text-gold/60">{label}</p>
      <div className="mt-[19px] border border-white/8 bg-[#090c20] px-[19px] py-[14px] font-mono text-[23px] tracking-[0.16em] text-white/85">{example}</div>
      <p className="mt-[23px] text-[17px] leading-[27px] text-white/50">{body}</p>
      <ul className="mt-[19px] space-y-[10px] border-t border-white/6 pt-[19px]">
        {points.map((point) => (
          <li key={point} className="flex gap-[10px] text-[14px] leading-[23px] text-white/40">
            <span className="mt-[8px] h-[5px] w-[5px] shrink-0 bg-gold/60" />
            <span>{point}</span>
          </li>
        ))}
      </ul>
    </article>
  );
}

function ReceiptCard({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <article className="border border-gold/15 bg-gold/5 p-[23px]">
      <h3 className="font-heading text-[17px] font-bold uppercase tracking-[0.12em] text-gold/80">{title}</h3>
      <p className="mt-[14px] text-[14px] leading-[23px] text-white/50">{children}</p>
    </article>
  );
}

function Question({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <article className="border border-white/8 bg-navy/45 p-[23px]">
      <h3 className="font-heading font-bold text-white/85">{title}</h3>
      <p className="mt-[10px] text-[14px] leading-[23px] text-white/45">{children}</p>
    </article>
  );
}
